name: Release Docker Image (Build and Push)

on:
  release:
    types: [published]

jobs:
  geoserver:
    if: ${{ contains(github.ref, 'geoserver_') }}
    runs-on: ubuntu-latest
    steps:
    - uses: winterjung/split@v2
      id: split
      with:
        separator: "_"
        msg: ${{ github.ref }}
    - uses: actions/checkout@v3
      with:
       ref: ${{ github.ref }}
    - uses: ./.github/actions/build_and_push
      with:
        image: "geoserver"
        branch: ${{ github.ref }}
        tag: ${{ steps.split.outputs._1 }}
        push: true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  postgis:
    if: ${{ contains(github.ref, 'postgis_') }}
    runs-on: ubuntu-latest
    steps:
    - uses: winterjung/split@v2
      id: split
      with:
        separator: "_"
        msg: ${{ github.ref }}
    - uses: actions/checkout@v3
      with:
       ref: ${{ github.ref }}
    - uses: ./.github/actions/build_and_push
      with:
        image: "postgis"
        branch: ${{ github.ref }}
        tag: ${{ steps.split.outputs._1 }}
        push: true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  nginx:
    if: ${{ contains(github.ref, 'nginx_') }}
    runs-on: ubuntu-latest
    steps:
    - uses: winterjung/split@v2
      id: split
      with:
        separator: "_"
        msg: ${{ github.ref }}
    - uses: actions/checkout@v3
      with:
       ref: ${{ github.ref }}
    - uses: ./.github/actions/build_and_push
      with:
        image: "nginx"
        branch: ${{ github.ref }}
        tag: ${{ steps.split.outputs._1 }}
        push: true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  data_dir_conf:
    if: ${{ contains(github.ref, 'data-dir-conf_') }}
    runs-on: ubuntu-latest
    steps:
    - uses: winterjung/split@v2
      id: split
      with:
        separator: "_"
        msg: ${{ github.ref }}
    - uses: actions/checkout@v3
      with:
       ref: ${{ github.ref }}
    - uses: ./.github/actions/build_and_push
      with:
        image: "data-dir-conf"
        branch: ${{ github.ref }}
        tag: ${{ steps.split.outputs._1 }}
        push: true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
  letsencrypt:
    if: ${{ contains(github.ref, 'letsencrypt_') }}
    runs-on: ubuntu-latest
    steps:
    - uses: winterjung/split@v2
      id: split
      with:
        separator: "_"
        msg: ${{ github.ref }}
    - uses: actions/checkout@v3
      with:
       ref: ${{ github.ref }}
    - uses: ./.github/actions/build_and_push
      with:
        image: "letsencrypt"
        branch: ${{ github.ref }}
        tag: ${{ steps.split.outputs._1 }}
        push: true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
